// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf2PDg18Q1HQOI_PSp_ODCYOdQe4b5LXo',
    appId: '1:1073120601990:web:fdc1a1292be68eb7942e07',
    messagingSenderId: '1073120601990',
    projectId: 'bus-location-a75a6',
    authDomain: 'bus-location-a75a6.firebaseapp.com',
    storageBucket: 'bus-location-a75a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxUntvuY6eu-zo-H2bwJE2448nHIZSDGE',
    appId: '1:1073120601990:android:5433e440268ac7fe942e07',
    messagingSenderId: '1073120601990',
    projectId: 'bus-location-a75a6',
    storageBucket: 'bus-location-a75a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0wLu_vIWrva97FFXtQXHBLrnIT3SriU0',
    appId: '1:1073120601990:ios:5eb43cb4827e9c15942e07',
    messagingSenderId: '1073120601990',
    projectId: 'bus-location-a75a6',
    storageBucket: 'bus-location-a75a6.appspot.com',
    iosBundleId: 'com.example.busLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0wLu_vIWrva97FFXtQXHBLrnIT3SriU0',
    appId: '1:1073120601990:ios:5eb43cb4827e9c15942e07',
    messagingSenderId: '1073120601990',
    projectId: 'bus-location-a75a6',
    storageBucket: 'bus-location-a75a6.appspot.com',
    iosBundleId: 'com.example.busLocation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf2PDg18Q1HQOI_PSp_ODCYOdQe4b5LXo',
    appId: '1:1073120601990:web:9afa8feb8ac71246942e07',
    messagingSenderId: '1073120601990',
    projectId: 'bus-location-a75a6',
    authDomain: 'bus-location-a75a6.firebaseapp.com',
    storageBucket: 'bus-location-a75a6.appspot.com',
  );
}
